name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Test
        run: npm run test

      - name: Build all apps
        run: npm run build

  storybook:
    name: Storybook & Chromatic
    runs-on: ubuntu-latest
    needs: lint-test-build
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - name: Build Storybook
        run: npx turbo build-storybook --filter=@platform/ui
      - name: Chromatic
        if: env.CHROMATIC_PROJECT_TOKEN
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes
        working-directory: packages/ui

  # TODO: enable once AWS credentials and ECR are configured
  # docker:
  #   name: Docker Build & Push
  #   runs-on: ubuntu-latest
  #   needs: lint-test-build
  #   if: github.ref == 'refs/heads/main'
  #   strategy:
  #     matrix:
  #       app: [host-shell, mfe-products, mfe-cart, mfe-user]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #     - uses: aws-actions/amazon-ecr-login@v2
  #       id: ecr
  #     - name: Build & push
  #       run: |
  #         docker build \
  #           --build-arg APP_NAME=${{ matrix.app }} \
  #           -f infra/docker/Dockerfile.app \
  #           -t ${{ steps.ecr.outputs.registry }}/platform/${{ matrix.app }}:${{ github.sha }} \
  #           -t ${{ steps.ecr.outputs.registry }}/platform/${{ matrix.app }}:latest \
  #           .
  #         docker push ${{ steps.ecr.outputs.registry }}/platform/${{ matrix.app }} --all-tags
